export const fichas = [
    { 
        idficha: 1,
        estado: 1,
        nombre: "Juan Pablo",
        apellido: "Fuentes", 
        fecha_nacimiento: "01 de Junio de 1982",
        alias: 'Tio Palo',
        email: "pablo@example.com", 
        edad: 44,
        cargo: "Sin Cargo",
        foto_usuario: "../images/pablo_user.jpeg",
        foto_ficha: "../images/user1.jpeg",
        foto_moto: "../images/user1.jpeg",
        marca_moto: "Yamaha",
        modelo_moto: "Virago 750",
        ano_moto: 1,
        telefono_emergencia: "",
        calidad: "Parchado"
    },
    { 
        idficha: 2,
        estado: 1,
        nombre: "Alejandro",
        apellido: "Vejar",  
        fecha_nacimiento: "",
        alias: 'Ale',
        email: "ale@example.com", 
        edad: 38,
        cargo: "Sargento en Armas",
        foto_usuario: "../images/ale_user.jpeg",
        foto_ficha: "../images/user1.jpeg",
        foto_moto: "../images/user1.jpeg",
        marca_moto: "Kawasaki",
        modelo_moto: "Vulcan 900",
        ano_moto: 1,
        telefono_emergencia: "",
        calidad: "Parchado"
    },
    { 
        idficha: 3,
        estado: 1,
        nombre: "Juan Jose",
        apellido: "Reyes",  
        fecha_nacimiento: "",
        alias: 'Jota',
        email: "jota@example.com", 
        edad: 37,
        cargo: "Sin Cargo",
        foto_usuario: "../images/jota_user.jpeg",
        foto_ficha: "../images/user1.jpeg",
        foto_moto: "../images/user1.jpeg",
        marca_moto: "Yamaha",
        modelo_moto: "Star 650",
        ano_moto: 1,
        telefono_emergencia: "",
        calidad: "Parchado"
    },
    { 
        idficha: 4,
        estado: 1,
        nombre: "Robinson",
        apellido: "Gonzalez",  
        fecha_nacimiento: "29 de Abril de 1983",
        alias: 'Lex',
        email: "lex@example.com", 
        edad: 43,
        cargo: "Tesorero",
        foto_usuario: "../images/lex_user.jpeg",
        foto_ficha: "../images/user1.jpeg",
        foto_moto: "../images/user1.jpeg",
        marca_moto: "Yamaha",
        modelo_moto: "",
        ano_moto: 1,
        telefono_emergencia: "",
        calidad: "Parchado"
    },
    { 
        idficha: 5,
        estado: 1,
        nombre: "Marcelo",
        apellido: "Brackamonte",  
        fecha_nacimiento: "",
        alias: 'Bracka',
        email: "bracka@example.com", 
        edad: 49,
        cargo: "Vice Presidente",
        foto_usuario: "../images/bracka_user.jpeg",
        foto_ficha: "../images/user1.jpeg",
        foto_moto: "../images/user1.jpeg",
        marca_moto: "Yamaha",
        modelo_moto: "Dragstar 1100",
        ano_moto: 1,
        telefono_emergencia: "",
        calidad: "Parchado"
    },
    { 
        idficha: 6,
        estado: 0,
        nombre: "Hugo",
        apellido: "-", 
        fecha_nacimiento: "", 
        alias: 'Chadu',
        email: "chadu@example.com", 
        edad: 56,
        cargo: "Sin Cargo",
        foto_usuario: "../images/chadu_user.jpeg",
        foto_ficha: "../images/user1.jpeg",
        foto_moto: "../images/user1.jpeg",
        marca_moto: "",
        modelo_moto: "",
        ano_moto: 1,
        telefono_emergencia: "",
        calidad: "Parchado"
    },
    { 
        idficha: 7,
        estado: 1,
        nombre: "Raul",
        apellido: "Salas", 
        fecha_nacimiento: "", 
        alias: 'Raul',
        email: "raul@example.com", 
        edad: 52,
        cargo: "Presidente",
        foto_usuario: "../images/raul_user.jpeg",
        foto_ficha: "../images/user1.jpeg",
        foto_moto: "../images/user1.jpeg",
        marca_moto: "Yamaha",
        modelo_moto: "Bold 950",
        ano_moto: 1,
        telefono_emergencia: "",
        calidad: "Parchado"
    },
    { 
        idficha: 8,
        estado: 1,
        nombre: "Arturo",
        apellido: "Zuñiga", 
        fecha_nacimiento: "", 
        alias: 'Arturo',
        email: "arturo@example.com", 
        edad: 38,
        cargo: "Secretario",
        foto_usuario: "../images/arturo_user.jpeg",
        foto_ficha: "../images/user1.jpeg",
        foto_moto: "../images/user1.jpeg",
        marca_moto: "Harley Davison",
        modelo_moto: "Street 750",
        ano_moto: 1,
        telefono_emergencia: "",
        calidad: "Parchado"
    },
    { 
        idficha: 9,
        estado: 1,
        nombre: "Troncoso",
        apellido: "-", 
        fecha_nacimiento: "", 
        alias: 'Satiro',
        email: "troncoso@example.com", 
        edad: 39,
        cargo: "Capitan de Ruta",
        foto_usuario: "../images/troncoso_user.jpeg",
        foto_ficha: "../images/user1.jpeg",
        foto_moto: "../images/user1.jpeg",
        marca_moto: "Yamaha",
        modelo_moto: "Star 900",
        ano_moto: 1,
        telefono_emergencia: "",
        calidad: "Parchado"
    },
    { 
        idficha: 10,
        estado: 1,
        nombre: "John",
        apellido: "-", 
        fecha_nacimiento: "", 
        alias: 'John',
        email: "arturo@example.com", 
        edad: 44,
        cargo: "Sin Cargo",
        foto_usuario: "../images/john_user.jpeg",
        foto_ficha: "../images/user1.jpeg",
        foto_moto: "../images/user1.jpeg",
        marca_moto: "Yamaha",
        modelo_moto: "Virago 1100",
        ano_moto: 1,
        telefono_emergencia: "",
        calidad: "Parchado"
    },
    { 
        idficha: 11,
        estado: 1,
        nombre: "Gerardo",
        apellido: "-", 
        fecha_nacimiento: "", 
        alias: 'Gera',
        email: "gera@example.com", 
        edad: 34,
        cargo: "Sin Cargo",
        foto_usuario: "../images/user1.jpeg",
        foto_ficha: "../images/user1.jpeg",
        foto_moto: "../images/user1.jpeg",
        marca_moto: "",
        modelo_moto: "",
        ano_moto: 1,
        telefono_emergencia: "",
        calidad: "Prospecto"
    },
    { 
        idficha: 12,
        estado: 1,
        nombre: "Francisco",
        apellido: "-", 
        fecha_nacimiento: "", 
        alias: 'Frank',
        email: "frank@example.com", 
        edad: 31,
        cargo: "Sin Cargo",
        foto_usuario: "../images/user1.jpeg",
        foto_ficha: "../images/user1.jpeg",
        foto_moto: "../images/user1.jpeg",
        marca_moto: "",
        modelo_moto: "",
        ano_moto: 1,
        telefono_emergencia: "",
        calidad: "Prospecto"
    },
    { 
        idficha: 13,
        estado: 1,
        nombre: "Petro",
        apellido: "-", 
        fecha_nacimiento: "", 
        alias: 'Petro',
        email: "petro@example.com", 
        edad: 46,
        cargo: "Sin Cargo",
        foto_usuario: "../images/user1.jpeg",
        foto_ficha: "../images/user1.jpeg",
        foto_moto: "../images/user1.jpeg",
        marca_moto: "Yamaha",
        modelo_moto: "Virago 750",
        ano_moto: 1,
        telefono_emergencia: "",
        calidad: "Prospecto"
    },
    { 
        idficha: 14,
        estado: 1,
        nombre: "Francisco",
        apellido: "-", 
        fecha_nacimiento: "", 
        alias: 'Pancho',
        email: "pancho@example.com", 
        edad: 29,
        cargo: "Sin Cargo",
        foto_usuario: "../images/user1.jpeg",
        foto_ficha: "../images/user1.jpeg",
        foto_moto: "../images/user1.jpeg",
        marca_moto: "",
        modelo_moto: "",
        ano_moto: 1,
        telefono_emergencia: "",
        calidad: "Prospecto"
    }
];